[project]
name = "sotck-sync"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "openpyxl>=3.1.5",
 "pandas>=2.2.3",
 "pyxlsb>=1.0.10",
 "xlsxwriter>=3.2.3",
]

[dependency-groups]
dev = ["pyinstaller>=6.13.0"]
